### ISSUE TITLE
HW1 Feedback

### ISSUE THREAD

**Issue by jvictorchen** [ChristopherLiu618/baruch-mfe-python-summer#1]
* MyList0: should use lower_case for variable names.
* `GetPrime` -> `get_primes`. Better use list comprehension than higher order functions.
* Check list is empty with `if my_list`, instead of `if my_list == []`
* `CaseInsensitiveEqual` -> `_case_insensitive_equal`
* Your case insensitive dictionary has O(1) complexity for get/set/delete. Could you make it O(1)? Otherwise dictionary lost its main benefit.

Score: A-

**Comment by ChristopherLiu618** [comment]
Thanks for the feedback!

> Your case insensitive dictionary has O(1) complexity for get/set/delete. Could you make it O(1)? Otherwise dictionary lost its main benefit.

Should create a dict whose keys are lower-case strings pointing to the UserDict keys, which are actual strings.

**Comment by jvictorchen** [comment]
Another way is to store the (original key, value) as value. For code example you can take a look at https://github.com/psf/requests/blob/bbc3d43522bcb1363050557655508d66bfebcfcf/requests/structures.py#L15
